version: '3.1'
services:
  stats-server:
    build: ./stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_STATS=stats
      - DB_HOST_STATS=stats-db
      - DB_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user

  ewm-service:
    build: ./ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - DB_EWM=serverEwm
      - DB_HOST_EWM=ewm-db
      - DB_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - STATS.URI=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=serverEwm
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user